'''
Author: rx-ted
Date: 2023-01-07 18:50:16
LastEditors: rx-ted
LastEditTime: 2023-01-07 20:44:36
'''
Import('RTT_ROOT')
Import('rtconfig')
from building import *


cwd  = GetCurrentDir()

src = []
CPPPATH = [cwd]

if GetDepend('RT_USING_ADC'):
    src+=[cwd+'/drv_adc.c']


if GetDepend('RT_USING_CAN'):
    src+=[cwd+'/drv_can.c']


if GetDepend('RT_USING_DAC'):
    src+=[cwd+'/drv_dac.c']


if GetDepend('RT_USING_PIN'):
    src+=[cwd+'/drv_gpio.c']


if GetDepend('RT_USING_HWTIMER'):
    src+=[cwd+'/drv_hwtimer.c']


if GetDepend('RT_USING_I2C'):
    src+=[cwd+'/drv_i2c.c']


if GetDepend('RT_USING_SPI'):
    src+=[cwd+'/drv_spi.c']


if GetDepend('RT_USING_UART'):
    src+=[cwd+'/drv_uart.c']

if GetDepend('RT_USING_WDT'):
    src+=[cwd+'/drv_wdt.c']

group = DefineGroup('drivers', src, depend = ['RT_USING_DEVICE'], CPPPATH = CPPPATH)

Return('group')
