'''
Author: rx-ted
Date: 2023-01-06 22:18:01
LastEditors: rx-ted
LastEditTime: 2023-01-08 01:04:19
'''
import rtconfig
from building import *

cwd = GetCurrentDir()

src = ['src/misc.c',
    'src/n32g4fr_bkp.c',    
    'src/n32g4fr_crc.c',
    'src/n32g4fr_dbg.c',
    'src/n32g4fr_dma.c',
    'src/n32g4fr_dvp.c',
    'src/n32g4fr_exti.c',
    'src/n32g4fr_flash.c',
    'src/n32g4fr_pwr.c',
    'src/n32g4fr_rcc.c',
    'src/n32g4fr_rtc.c',
    'src/n32g4fr_sdio.c',
    'src/n32g4fr_tim.c',
    'src/n32g4fr_tsc.c']

path = [cwd + '/inc']

CPPDEFINES = ['USE_HAL_DRIVER', rtconfig.N32_TYPE]

if GetDepend(['RT_USING_PIN']):
    src += ['src/n32g4fr_gpio.c']

if GetDepend(['RT_USING_CAN']):
    src += ['src/n32g4fr_can.c']

if GetDepend(['RT_USING_I2C']):
    src += ['src/n32g4fr_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['src/n32g4fr_qspi.c']
    src += ['src/n32g4fr_spi.c']
    
if GetDepend(['RT_USING_SERIAL']):
    src += ['src/n32g4fr_usart.c']

if GetDepend(['RT_USING_WDT']):
    src += ['src/n32g4fr_iwdg.c']
    src += ['src/n32g4fr_wwdg.c']

if GetDepend(['RT_USING_ADC']):
    src += ['src/n32g4fr_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['src/n32g4fr_dac.c']

group = DefineGroup('USE_HAL', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
